recombinator: recombinator.cpp
	g++ -g recombinator.cpp -o recombinator -O2 -std=c++17
recombinator2: recombinator2.cpp
	g++ -g recombinator2.cpp -o recombinator2 -O2 -std=c++17
recombinator3: recombinator3.cpp
	g++ -g recombinator3.cpp -o recombinator3 -O2 -std=c++17
